import { Geist, Geist_Mono,Poppins, Lato } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";

const lato = Lato({
  weight: ['300', '400', '700'], 
  subsets: ['latin'],
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  weight: ['300', '400', '600'],   
  subsets: ['latin'],              
});;

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`} cz-shortcut-listen="true">
        {children}
      </body>
    </html>
  );
}
